### ISSUE TITLE
Da fixare nella prova 1

### ISSUE THREAD

**Issue by N1den** [fizzi01/MisureRel#86]
Pagina 10: 

- [x] abbiamo impostato la portata dello strumento a 6 cifre e mezzo premendo sul tasto "Shift" e poi sul tasto "Auto/Man"
- [x] abbiamo lavorato in modalità due morsetti attivata premendo sul pulsante Ω2W

Pagina 12:

- [x]  abbiamo lavorato in modalità 4 terminali attivata premendo prima su "Shift" e poi sul pulsante Ω2W

Pagina 13:

- [x]  all'ultima riga, non abbiamo trovato una stima pari a 1,648. Quello è il valore della prima delle 10 misure. Sostituire con la media dei 10 valori misurati ?
- [x]  Per quanto riguarda la compatibilità tra le misure, togliamo quel discorso e l'immagine visto che non esce come previsto ? 

Pagina 14:

- [x] Ricalcolare l'errore della misura a 2W in base al valore medio calcolato prima e quindi l'incertezza relativa
- [x] Sistemare la visualizzazione delle formule (Modulo e pedici)
- [x] Ricalcolare l'accuratezza relativa a della misura 4W perchè è sbagliata. Dovrebbe essere 98%

Pagina 15:

- [x] testo doppio "L'esercitazione è iniziata..."

Pagina 16

- [x]  il procedimento della correzione OPEN/SHORT è scritto a metà nella sezione "Impedenze". Spostare tale spiegazione ad inizio pagina dove viene nominato e scrivere il procedimento COMPLETO che vedendo dal video dovrebbe essere:
     Ci mettiamo a frequenza 1KHz
    Non collego nulla ai morsetti cioè lascio in circuito aperto, premo pulsante blu, premo sul pulsante "4", premo ENTER e aspetto che 
          esca "Open correction complete"
      Cortocircuito i morsetti l'uno con l'altro, premo pulsante blu, premo sul pulsante "5", premo ENTER e attendo "Short correction  complete"
- [x]  manca il tempo di misura medio
- [x]  piccoli errori ortografici
- [x] si fa riferimento a diagrammi di bode che non ci sono nel file

Pagina 16-17:

- [x] Sistemare nei dovuti punti queste informazioni scritte bene su come impostare i parametri da visualizzare.
- [x]  per impostare i parametri per la resistenza si preme su "Meas Prmtr", si seleziona il primo R, si preme ENTER, si seleziona X e si preme ENTER

- [x] per impostare i parametri da visualizzare per la capacità si preme su "Meas Prmtr", si seleziona Cp, si preme Enter, si seleziona Rp, si preme enter. E poi si preme Cp, enter, si seleziona D, enter

**Comment by fizzi01** [comment]
Chi risolve i problemi spunti il problema qui

**Comment by fizzi01** [comment]
> [ ] Sistemare la visualizzazione delle formule (Modulo e pedici)

Pensavo di aver sistemato la maggior parte delle formule. Che manca?

**Comment by N1den** [comment]
C'è un inizio pedice con parentesi ( e il resto sta a livello normale. E poi il valore assoluto non prende per intero numeratore e denominatore @fizzi01

**Comment by fizzi01** [comment]
> C'è un inizio pedice con parentesi ( e il resto sta a livello normale. E poi il valore assoluto non prende per intero numeratore e denominatore @fizzi01

Dammi una linea di esempio
